### PR TITLE
Updates to ChatFilter List

### PR DESCRIPTION
**Pull request by BearsMan**
in case I find a new one I will add it to my branch and PR it here

### CODE REVIEW

**Comment by BearsMan** [comment]
Tested and ready for Merge

**Comment by BearsMan** [comment]
Added more rules from my fork set to Merge

**Comment by BearsMan** [comment]
@kevinpetit whenever u have time to merge no rush

**Comment by BearsMan** [comment]
found more rules

**Comment by kevinpetit** [comment]
I'm currently without reliable internet, so my response time is a bit off :)

**Comment by BearsMan** [comment]
thanks, @kevinpetit :) sorry about that but I was testing a lot of them to make sure they work

**Comment by kevinpetit** [comment]
I'm fully back on reliable internet now :D

**Pull request merged**
