### PR TITLE
Updates to Chat Filter Again

### PR DESCRIPTION
**Pull request by BearsMan**
Fixes Pull Request #60 by rewriting the list from scratch 

Changed Unicode type to UTF-16 LE instead of UTF-8 Unicode 

This was done to prevent Gold sellers from spamming the same ads in Kamadan even if its the same type that was found originally

### CODE REVIEW

**Comment by BearsMan** [comment]
New Edited filters are fixed corrected and ready for a merge if I find any weird links I will add in a new PR

**Comment by BearsMan** [comment]
the MMoGamersMarket is still there I believe I have to change the coding around in the ini

**Comment by BearsMan** [comment]
do NOT Merge this until then for a bit I want to make sure its filtered out in-game

**Comment by BearsMan** [comment]
do not merge yet I want to make sure I fixed it correctly

**Comment by BearsMan** [comment]
just merge this ill see what I can do in another PR soon

**Comment by BearsMan** [comment]
I think we have found an issue in the type of file ChatFilter.ini is saved to: Pick "save as" and use the file name ChatFilter.ini and save it at c:\users\<username>\my documents\guild wars\ in UTF16 LE  encoding, which seems to work best others seem to not count some characters as the same, even if they are, but reside in multiple sections of the unicode character set (really that is a guess, but, only explanation i can think of.) 
DO NOT USE UTF-16 BE ENCODING IT WILL CRASH GUILD WARS
If you are in the right spot u will see the screenshots and templates folders.

The pic showed here on how to re-save and change type: [https://i.imgur.com/OdFxg0z.png](url)

**Comment by BearsMan** [comment]
Re saved Filter to UTF-16 LE encoding from now on to avoid spams shown: Looney shows the pic on the Legacy page if u go see

**Comment by BearsMan** [comment]
just merge this the support for UTF-16 doesn't work right

**Comment by BearsMan** [comment]
I only wanted to see if Github will show saved changes made in a different encoder

**Comment by BearsMan** [comment]
I re-edited the filter in utf 8 but do not overwrite again in Github I would suggest u keep 2 back up of ChatFilter.ini
1 in UTF-8 and the other in UTF-16 LE

DO NOT OVERWRITE THE UTF-16 ENCODING

**Comment by BearsMan** [comment]
the list in UTF-16 is the same as UTF-8 List I only added the backup list to make sure it doesn't make any changes to original

**Comment by BearsMan** [comment]
The list has been rewritten and ready for merge this I also deleted 2x handwritten filters of the same files to avoid conflicts with each other

**Comment by BearsMan** [comment]
https://github.com/BearsMan/legacy-chatfilter/blob/71f25493e38eef6dda6cf248efc9d2db1f716d75/ChatFilter.ini

full list of whats added in the chatfilter

**Comment by BearsMan** [comment]
https://github.com/kevinpetit/legacy-chatfilter/blob/6f2ae40d524966f4b228b4f9d49f51ac95f37aac/ChatFilter.ini

rewritten list

**Comment by kevinpetit** [comment]
Wow, this was... a wild ride. Merging!

**Comment by BearsMan** [comment]
yea it was a very wide ride come to find out UTF-16 LE is better because it does not allow for more then 1 copy of the same ad

**Pull request merged**
